version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack-app
    ports:
      - "6379:6379"
      - "8001:8001"

  app:
    build: ./app
    container_name: streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}